### ISSUE TITLE
给点小小的建议

### ISSUE THREAD

**Issue by SmallOyster** [MrWooz/GZ-subway#1]
给一点小小的建议：

可以在选择站点的地方加上“站点号”，以便让不识汉字的鬼佬也能使用这个插件！

嗯……问多一个问题：作者本人是广州人吗？

**Comment by MrWooz** [comment]
好的！谢谢！这段时间工作较忙，会改进。本人在广州生活工作。

**Comment by SmallOyster** [comment]
@MrWooz 

我也开了个pull request，改了一些站间距。欢迎采纳哈~

**Comment by MrWooz** [comment]
十分感谢！！！您是直接测距的？！

**Comment by SmallOyster** [comment]
我也是上贴吧拿的 :joy:

只不过那个人也是用地图的直线测距功能测出来的

**Comment by MrWooz** [comment]
好的，还是十分感谢！
